/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: "var(--primary)",
        primaryForeground: "var(--primary-foreground)",
        primaryHover: "var(--primary-hover)",
        secondary: "var(--secondary)",
        secondaryForeground: "var(--secondary-foreground)",
        secondaryHover: "var(--secondary-hover)",
        accent: "var(--accent)",
        accentForeground: "var(--accent-foreground)",
        accentHover: "var(--accent-hover)",
      },
    },
  },
  safelist: [
    "border-lime-500",
    "hover:bg-lime-500",
    "border-green-800",
    "hover:bg-green-800",
    "border-green-500",
    "hover:bg-green-500",
    "border-emerald-500",
    "hover:bg-emerald-500",
    "border-indigo-500",
    "hover:bg-indigo-500",
    "border-indigo-800",
    "hover:bg-indigo-800",
    "border-blue-500",
    "hover:bg-blue-500",
    "border-sky-500",
    "hover:bg-sky-500",
    "border-cyan-500",
    "hover:bg-cyan-500",
    "border-yellow-500",
    "hover:bg-yellow-500",
    "border-orange-500",
    "hover:bg-orange-500",
    "border-red-500",
    "hover:bg-red-500",
    "border-slate-500",
    "hover:bg-slate-500",
    "border-violet-500",
    "hover:bg-violet-500",
    "border-pink-500",
    "hover:bg-pink-500",
    "border-amber-500",
    "hover:bg-amber-500",
    "border-stone-500",
    "hover:bg-stone-500",
    "border-purple-500",
    "hover:bg-purple-500",
  ],
  plugins: [],
};
